name       : cycler
version    : 0.10.0
release    : 5
source     :
    - https://github.com/matplotlib/cycler/archive/v0.10.0.tar.gz : b6d217635e03024196225367b1a438996dbbf0271bec488f00584f0e7dc15cfa
license    : BSD-3-Clause
component  : programming.python
summary    : Composable style cycles
description: |
    Composable style cycles
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    for py in "python2" "python3.5"; do
        ${py} setup.py build
    done
install    : |
    for py in "python2" "python3.5"; do
        ${py} setup.py install --root=%installroot%
    done
