name       : cycler
version    : 0.9.0
release    : 1
source     :
    - https://pypi.python.org/packages/source/C/Cycler/cycler-0.9.0.tar.gz : 96dc4ddf27ef62c09990c6196ac1167685e89168042ec0ae4db586de023355bc
license    : BSD-3-Clause
summary    : Composable style cycles
description: |
    Composable style cycles
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.4)
    - python-setuptools
    - python3-setuptools
build      : |
    for py in "python2" "python3.4"; do
        ${py} setup.py build
    done
install    : |
    for py in "python2" "python3.4"; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
